#######################
# Datadog Configuration
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.apiKey=YOUR_DATADOG_API_KEY
management.datadog.metrics.export.uri=https://api.datadoghq.com
################################
################################
# Database configuration
spring.data.neo4j.uri=
# Explicitly set the database name
spring.data.neo4j.database=neo4j
spring.data.neo4j.authentication.username=
spring.data.neo4j.authentication.password=
#########################################
# Enable query logging
logging.level.org.springframework.data.neo4j=DEBUG
logging.level.org.neo4j.driver=DEBUG
######################################
# Tell migrations where to look
org.neo4j.migrations.locations-to-scan=classpath:neo4j
# Neo4j Migrations
org.neo4j.migrations.database=neo4j
org.neo4j.migrations.enabled=true